version: '2.1'
orbs:
  python: circleci/python@3.10.8
jobs:
  build:
    working_directory: ~/services/web/
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            python -m unittest discover
          name: Test
workflows:
  main:
    jobs:
      - build