version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    working_directory: ~/viwish_backend/services/web
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            ls
          name: Test
workflows:
  main:
    jobs:
      - build