version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  unit_tests:
    working_directory: ~/viwish_backend/services/web
    executor: python/default
    steps:
      - checkout
      - run:
          name: Go to Services Web Folder
          command: |
            cd services/web
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install --no-cache-dir -r services/web/requirements.txt
      - run: 
          name: Virtual Env
          command: |
            python -m venv ./venv
            . venv/bin/activate
      - run:
          name: Copy .env
          command: |
            cp .env.dev-sample .env.dev
      - run:
          name: Run Unit Tests 
          command: |
             python3 -m unittest discover -s services/web
workflows:
  main:
    jobs:
      - unit_tests