version: '2.1'
orbs:
  python: circleci/python@2.1.1
jobs:
  unit_tests:
    working_directory: ~/viwish_backend/services/web
    executor: python/default
    steps:
      - checkout
      - run:
          name: Go to Services Web Folder
          command: |
            cd services/web
      - run:
          name: Install dependencies
          command: |
            pip install -r services/web/requirements.txt
      - run:
          name: Run Unit Tests
          command: |
             python3 -m unittest discover
workflows:
  main:
    jobs:
      - unit_tests