from abc import ABC


class AbstractValidationRules(ABC):

    schema: dict = ...
    http_error_code: int = ...
    api_error_code: int = ...
    api_error_event: str = ...
    documentation: str = ...
